SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `avalon`;
USE `avalon`;

CREATE TABLE IF NOT EXISTS `member`(
	id INT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(128) NOT NULL,
    lastName VARCHAR(128) NOT NULL,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(64) NOT NULL,
    bio VARCHAR(512),
    gamesPlayed INT DEFAULT 0
)engine = innoDB;

CREATE TABLE IF NOT EXISTS `moderator`(
	id INT PRIMARY KEY,
    CONSTRAINT moderatorfk_1
		FOREIGN KEY(id)
        REFERENCES `member`(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
)engine = innoDB;

CREATE TABLE IF NOT EXISTS `admin`(
	id INT PRIMARY KEY,
    CONSTRAINT adminfk_1
		FOREIGN KEY(id)
        REFERENCES `moderator`(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
)engine = innoDB;

CREATE TABLE IF NOT EXISTS `game`(
	id INT AUTO_INCREMENT PRIMARY KEY,
    hosted DATETIME NOT NULL DEFAULT NOW(),
    ended DATETIME DEFAULT NULL,
    ongoing BOOLEAN NOT NULL DEFAULT FALSE,
    cancelled BOOLEAN NOT NULL DEFAULT FALSE,
    friendsOnly BOOLEAN NOT NULL DEFAULT FALSE,
    minPlayers INT NOT NULL DEFAULT 5,
    maxPlayers INT NOT NULL DEFAULT 10,
    targeting BOOLEAN NOT NULL DEFAULT FALSE,
    ladyOfTheLake BOOLEAN NOT NULL DEFAULT FALSE,
    host INT,
    CONSTRAINT gamefk_1
		FOREIGN KEY (`host`)
        REFERENCES member(`id`)
        ON UPDATE CASCADE
        ON DELETE SET NULL
) engine = innoDB;

CREATE TABLE IF NOT EXISTS `gamePlayers` (
	gameId INT,
    memberId INT,
    character VARCHAR(32) DEFAULT NULL,
    immuneToLady BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (gameId, memberId),
    CONSTRAINT gamePlayersfk_1
		FOREIGN KEY(`gameId`)
        REFERENCES game(`id`)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
	CONSTRAINT gamePlayersfk_2
		FOREIGN KEY(`memberId`)
        REFERENCES member(`id`)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) engine = innoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;